### ISSUE TITLE
email validation

### ISSUE THREAD

**Issue by onwordi** [FAC-Sixteen/Sparks#20]
Great that you've included client-side validation!

I did however put in `hello@test.com` and was told this was invalid. Maybe take a look at your regex, as once I removed the `pattern="/[-.\w]+@([\w-]+\.)+[\w-]{2,20}/gi"` the form submitted

**Comment by dubhcait** [comment]
I'm so silly, I actually saw that and fixed it locally and never push it to master. Silly me. 
It's because of the pattern attribute, it doesn't read Regex flags. the /gi
